export const PERSONAS = {
  executive: {
    id: 'executive',
    label: 'Executive',
    description: 'Regional decision maker',
    scope: 'region',
    homeScope: 'North region',
    allowedDomains: ['sales', 'marketing', 'inventory', 'finance'],
    restrictedFields: ['customer_email', 'payment_token', 'supplier_terms'],
    decisionRights: ['budget_reallocation', 'replenishment_priority', 'regional_pacing'],
  },
  'store-manager': {
    id: 'store-manager',
    label: 'Store manager',
    description: 'Store 042 operator',
    scope: 'store',
    homeScope: 'Store 042 · Bengaluru Central',
    allowedDomains: ['sales', 'inventory'],
    restrictedFields: ['customer_email', 'payment_token', 'campaign_audience', 'supplier_terms', 'regional_margin'],
    decisionRights: ['local_merchandising', 'stock_transfer_request', 'staffing_shift'],
  },
  'marketing-analyst': {
    id: 'marketing-analyst',
    label: 'Marketing analyst',
    description: 'Growth and attribution analyst',
    scope: 'region',
    homeScope: 'North region · paid media',
    allowedDomains: ['sales', 'marketing'],
    restrictedFields: ['customer_email', 'payment_token', 'supplier_terms'],
    decisionRights: ['campaign_pacing', 'audience_experiment', 'attribution_review'],
  },
};

export const SOURCE_CATALOG = [
  {
    id: 'sales-ledger',
    name: 'Sales ledger / ERP',
    domain: 'Sales',
    cadence: 'Daily · 06:00 IST',
    grain: 'Order line × store × SKU × day',
    lastRefresh: '2026-08-30T20:10:00+05:30',
    ageMinutes: 50,
    freshnessLabel: '50 min ago',
    freshnessStatus: 'fresh',
    sla: 'within 6h SLA',
    qualityScore: 99.2,
    coverage: 'Jan 2024 → today',
    rowSecurity: 'store_id entitlement',
    restrictedFields: ['customer_email', 'payment_token'],
    lineage: ['erp.order_lines', 'semantic.daily_sales'],
  },
  {
    id: 'marketing-platform',
    name: 'Marketing platform',
    domain: 'Marketing',
    cadence: 'Hourly · :15',
    grain: 'Campaign × channel × hour',
    lastRefresh: '2026-08-30T22:00:00+05:30',
    ageMinutes: 40,
    freshnessLabel: '40 min ago',
    freshnessStatus: 'fresh',
    sla: 'within 2h SLA',
    qualityScore: 94.8,
    coverage: 'Sep 2025 → today',
    rowSecurity: 'region entitlement',
    restrictedFields: ['campaign_audience'],
    lineage: ['ads.hourly_campaign_stats', 'semantic.paid_demand'],
  },
  {
    id: 'inventory-wms',
    name: 'Inventory / WMS',
    domain: 'Supply',
    cadence: 'Every 15 min',
    grain: 'SKU × location × interval',
    lastRefresh: '2026-08-30T22:28:00+05:30',
    ageMinutes: 12,
    freshnessLabel: '12 min ago',
    freshnessStatus: 'fresh',
    sla: 'within 30m SLA',
    qualityScore: 98.6,
    coverage: 'Apr 2024 → today',
    rowSecurity: 'location entitlement',
    restrictedFields: ['supplier_terms'],
    lineage: ['wms.inventory_snapshots', 'semantic.in_stock_rate'],
  },
];

export const KPI_CATALOG = [
  {
    id: 'net-revenue',
    label: 'Net revenue',
    shortLabel: 'Revenue',
    unit: 'INR',
    definition: 'Completed order value less returns, cancellations, and discounts.',
    formula: 'SUM(completed_line_value) - SUM(returns) - SUM(discounts)',
    grain: 'Store × SKU × day',
    refresh: 'Daily after ERP close',
    materiality: { absolute: 75000, relativePercent: 5, zScore: 2 },
    drivers: ['price', 'volume', 'mix', 'stockouts', 'paid-demand'],
    sourceIds: ['sales-ledger', 'inventory-wms', 'marketing-platform'],
    access: { executive: 'region', 'store-manager': 'Store 042', 'marketing-analyst': 'region' },
  },
  {
    id: 'units-sold',
    label: 'Units sold',
    shortLabel: 'Units',
    unit: 'units',
    definition: 'Net completed units after cancellations and returns.',
    formula: 'SUM(completed_units) - SUM(returned_units)',
    grain: 'Store × SKU × day',
    refresh: 'Daily after ERP close',
    materiality: { absolute: 500, relativePercent: 4, zScore: 2 },
    drivers: ['traffic', 'conversion', 'stockouts', 'mix'],
    sourceIds: ['sales-ledger', 'inventory-wms'],
    access: { executive: 'region', 'store-manager': 'Store 042', 'marketing-analyst': 'region' },
  },
  {
    id: 'average-order-value',
    label: 'Average order value',
    shortLabel: 'AOV',
    unit: 'INR',
    definition: 'Net revenue divided by completed orders.',
    formula: 'net_revenue / completed_orders',
    grain: 'Store × day',
    refresh: 'Daily after ERP close',
    materiality: { absolute: 50, relativePercent: 3, zScore: 2 },
    drivers: ['price', 'mix', 'basket-size'],
    sourceIds: ['sales-ledger'],
    access: { executive: 'region', 'store-manager': 'Store 042', 'marketing-analyst': 'region' },
  },
  {
    id: 'paid-conversion',
    label: 'Paid conversion',
    shortLabel: 'Conversion',
    unit: 'percent',
    definition: 'Attributed completed orders divided by paid sessions, deduplicated by click id.',
    formula: 'dedup(attributed_orders) / paid_sessions',
    grain: 'Campaign × channel × day',
    refresh: 'Hourly',
    materiality: { absolute: 0.3, relativePercent: 6, zScore: 2 },
    drivers: ['traffic', 'landing-page', 'offer', 'attribution-quality'],
    sourceIds: ['marketing-platform', 'sales-ledger'],
    access: { executive: 'region', 'store-manager': 'restricted', 'marketing-analyst': 'region' },
  },
  {
    id: 'in-stock-rate',
    label: 'In-stock rate',
    shortLabel: 'In-stock',
    unit: 'percent',
    definition: 'Weighted share of demand intervals where an active SKU is available at the selling location.',
    formula: 'available_demand_intervals / active_demand_intervals',
    grain: 'SKU × location × 15-minute interval',
    refresh: 'Every 15 minutes',
    materiality: { absolute: 1.5, relativePercent: 2, zScore: 2 },
    drivers: ['supplier-delay', 'replenishment', 'allocation', 'forecast-bias'],
    sourceIds: ['inventory-wms', 'sales-ledger'],
    access: { executive: 'region', 'store-manager': 'Store 042', 'marketing-analyst': 'restricted' },
  },
];

export const SEMANTIC_CONTRACT = {
  contractId: 'kpi-intelligence-demo-v0.1',
  version: '0.1.0',
  owner: 'Commercial Analytics',
  lastReviewed: '2026-08-28',
  calendar: 'IST retail week · Monday–Sunday · completed local day only',
  rules: [
    'Never compare an incomplete local day with a completed baseline day.',
    'A movement is material when business impact and either relative change or z-score pass threshold.',
    'A driver is an explanation only when its evidence covers the same period and entitlement scope.',
    'When evidence conflicts or history is sparse, preserve hypotheses but abstain from causal language and irreversible actions.',
  ],
  kpis: KPI_CATALOG,
};

const revenueDropKpis = [
  { id: 'net-revenue', current: 1240000, baseline: 1357000, change: -117000, changePercent: -8.6, display: '₹12.4L', baselineDisplay: '₹13.6L', status: 'material' },
  { id: 'units-sold', current: 18420, baseline: 19371, change: -951, changePercent: -4.9, display: '18,420', baselineDisplay: '19,371', status: 'material' },
  { id: 'average-order-value', current: 67.32, baseline: 70.03, change: -2.71, changePercent: -3.9, display: '₹67.32', baselineDisplay: '₹70.03', status: 'watch' },
  { id: 'paid-conversion', current: 2.8, baseline: 3.1, change: -0.3, changePercent: -9.7, display: '2.8%', baselineDisplay: '3.1%', status: 'watch' },
  { id: 'in-stock-rate', current: 91.4, baseline: 94.8, change: -3.4, changePercent: -3.6, display: '91.4%', baselineDisplay: '94.8%', status: 'material' },
];

const contradictionKpis = [
  { id: 'net-revenue', current: 1288000, baseline: 1357000, change: -69000, changePercent: -5.1, display: '₹12.9L', baselineDisplay: '₹13.6L', status: 'material' },
  { id: 'units-sold', current: 18120, baseline: 19371, change: -1251, changePercent: -6.5, display: '18,120', baselineDisplay: '19,371', status: 'material' },
  { id: 'average-order-value', current: 71.08, baseline: 70.03, change: 1.05, changePercent: 1.5, display: '₹71.08', baselineDisplay: '₹70.03', status: 'stable' },
  { id: 'paid-conversion', current: 3.4, baseline: 3.1, change: 0.3, changePercent: 9.7, display: '3.4%', baselineDisplay: '3.1%', status: 'positive' },
  { id: 'in-stock-rate', current: 93.2, baseline: 94.8, change: -1.6, changePercent: -1.7, display: '93.2%', baselineDisplay: '94.8%', status: 'watch' },
];

const newMarketKpis = [
  { id: 'net-revenue', current: 142000, baseline: 119900, change: 22100, changePercent: 18.4, display: '₹1.42L', baselineDisplay: '₹1.20L', status: 'signal' },
  { id: 'units-sold', current: 1880, baseline: 1590, change: 290, changePercent: 18.2, display: '1,880', baselineDisplay: '1,590', status: 'signal' },
  { id: 'average-order-value', current: 75.53, baseline: 75.41, change: 0.12, changePercent: 0.2, display: '₹75.53', baselineDisplay: '₹75.41', status: 'stable' },
  { id: 'paid-conversion', current: 2.2, baseline: 2.0, change: 0.2, changePercent: 10, display: '2.2%', baselineDisplay: '2.0%', status: 'signal' },
  { id: 'in-stock-rate', current: 96.1, baseline: 95.7, change: 0.4, changePercent: 0.4, display: '96.1%', baselineDisplay: '95.7%', status: 'stable' },
];

export const SCENARIOS = {
  'revenue-drop': {
    id: 'revenue-drop',
    label: 'Material revenue drop',
    description: 'Known multi-factor movement with enough aligned history.',
    periodLabel: 'Week 35 · Aug 24–30, 2026 vs Week 34',
    primaryKpiId: 'net-revenue',
    headline: 'Net revenue fell 8.6% week on week',
    subheadline: '₹1.17L below the comparable baseline, with availability the largest controllable signal.',
    observed: 1240000,
    baseline: 1357000,
    delta: -117000,
    changePercent: -8.6,
    zScore: -2.3,
    historyDays: 182,
    comparableDays: 26,
    baselineType: 'same-region seasonal baseline',
    materiality: { absoluteImpact: '₹1.17L', threshold: '₹75k', relative: '-8.6%', thresholdRelative: '±5%', passed: true },
    confidence: { score: 0.88, label: 'High', status: 'ready', reason: 'Three sources are fresh, aligned to the same week, and 26 comparable days support the baseline.' },
    sparseHistory: false,
    contradictions: [],
    kpis: revenueDropKpis,
    drivers: [
      { id: 'stockouts', label: 'Availability / stockouts', category: 'Supply', contributionPercent: 37, contributionValue: -43300, signal: 'In-stock rate fell 94.8% → 91.4%; 12 high-velocity SKUs were unavailable at least 4 hours.', method: 'Contribution analysis + inventory join', controllability: 'high', evidenceIds: ['ev-inventory-rate', 'ev-stockout-skus'], confidence: 0.91 },
      { id: 'volume', label: 'Units / volume', category: 'Demand', contributionPercent: 28, contributionValue: -32800, signal: 'Net units declined 4.9%, concentrated in the same stores and SKUs with lost availability.', method: 'Deterministic bridge', controllability: 'medium', evidenceIds: ['ev-sales-ledger', 'ev-stockout-skus'], confidence: 0.89 },
      { id: 'mix', label: 'Product mix', category: 'Merchandising', contributionPercent: 18, contributionValue: -21100, signal: 'Premium mix softened 2.6 points; lower-value basics made up more of the basket.', method: 'Mix decomposition', controllability: 'medium', evidenceIds: ['ev-mix-shift'], confidence: 0.78 },
      { id: 'paid-demand', label: 'Paid demand', category: 'Marketing', contributionPercent: 11, contributionValue: -12900, signal: 'Paid sessions declined 6.2%; click-through stayed stable, so the signal is top-of-funnel volume rather than creative fatigue.', method: 'Statistical comparison + retrieval', controllability: 'high', evidenceIds: ['ev-paid-demand'], confidence: 0.74 },
      { id: 'price', label: 'Price / discount', category: 'Commercial', contributionPercent: 6, contributionValue: -7000, signal: 'Realized price was 1.6% lower after a planned weekend discount.', method: 'Price-volume-mix bridge', controllability: 'high', evidenceIds: ['ev-sales-ledger', 'ev-promo-calendar'], confidence: 0.86 },
    ],
    evidence: [
      { id: 'ev-sales-ledger', sourceId: 'sales-ledger', title: 'Sales ledger closes the movement', finding: 'Revenue ₹12.4L vs ₹13.6L baseline; units −4.9%; completed orders are deduplicated.', status: 'aligned', coverage: '100% of region · Aug 24–30', method: 'Deterministic SQL-shaped aggregation', lineage: 'erp.order_lines → semantic.daily_sales → revenue_bridge' },
      { id: 'ev-inventory-rate', sourceId: 'inventory-wms', title: 'Availability moved with demand loss', finding: 'In-stock rate −3.4 points; 12 high-velocity SKUs account for 71% of lost availability intervals.', status: 'aligned', coverage: '98.6% snapshots · Store/SKU grain', method: 'Inventory join + contribution analysis', lineage: 'wms.inventory_snapshots → semantic.in_stock_rate → stockout_contribution' },
      { id: 'ev-stockout-skus', sourceId: 'inventory-wms', title: 'Lost sales cluster in a small SKU set', finding: 'Top 12 stockout SKUs explain ₹43.3k of the modeled revenue gap.', status: 'aligned', coverage: '12 SKUs · 8 stores', method: 'SKU contribution ranking', lineage: 'semantic.in_stock_rate + semantic.daily_sales → sku_bridge' },
      { id: 'ev-mix-shift', sourceId: 'sales-ledger', title: 'Basket mix softened', finding: 'Premium category share declined 2.6 points while basics rose.', status: 'aligned', coverage: '100% of order lines', method: 'Mix decomposition', lineage: 'semantic.daily_sales → category_mix_bridge' },
      { id: 'ev-paid-demand', sourceId: 'marketing-platform', title: 'Paid demand is a secondary signal', finding: 'Paid sessions −6.2%; click-through stable; attributed orders are deduplicated by click id.', status: 'supporting', coverage: '94.8% campaign rows · hourly', method: 'Statistical comparison', lineage: 'ads.hourly_campaign_stats → semantic.paid_demand → revenue_bridge' },
      { id: 'ev-promo-calendar', sourceId: 'sales-ledger', title: 'Planned promotion explains price pressure', finding: 'Weekend discount lowered realized price 1.6%; no unplanned price override detected.', status: 'supporting', coverage: 'Promo calendar + order lines', method: 'Business-rule lookup', lineage: 'commercial.promo_calendar → price_bridge' },
    ],
    actions: [
      { id: 'expedite-stock', driverId: 'stockouts', lever: 'Availability', action: 'Expedite or transfer the 12 high-velocity SKUs into the eight affected stores.', expectedImpact: 'Recover ₹31k–₹44k weekly revenue if in-stock returns above 94%.', owner: 'Supply planning', confidence: 'High', monitor: 'In-stock rate and lost-sales estimate every 4 hours.', rights: ['executive', 'store-manager'] },
      { id: 'protect-demand', driverId: 'paid-demand', lever: 'Demand pacing', action: 'Keep efficient campaigns live and shift only 10% of spend toward the in-stock category set.', expectedImpact: 'Protect ₹8k–₹13k of demand without amplifying stockout waste.', owner: 'Growth lead', confidence: 'Medium', monitor: 'Paid conversion, stock-aware ROAS, and spend by available SKU.', rights: ['executive', 'marketing-analyst'] },
      { id: 'review-mix', driverId: 'mix', lever: 'Merchandising', action: 'Place two premium attach items beside the top basic SKUs in Store 042 and test the bundle for seven days.', expectedImpact: 'Recover 0.8–1.2 points of premium mix; expected revenue lift ₹4k–₹7k.', owner: 'Store 042 manager', confidence: 'Medium', monitor: 'Premium share, AOV, and bundle sell-through.', rights: ['store-manager'] },
      { id: 'hold-discount', driverId: 'price', lever: 'Promo guardrail', action: 'Do not extend the weekend discount until the availability gap is cleared.', expectedImpact: 'Avoid another ₹7k of modeled price leakage.', owner: 'Commercial lead', confidence: 'Medium', monitor: 'Realized price and promo-adjusted revenue.', rights: ['executive', 'marketing-analyst'] },
    ],
  },
  'contradictory-evidence': {
    id: 'contradictory-evidence',
    label: 'Conflicting evidence',
    description: 'The feeds disagree, so the engine pauses causal claims.',
    periodLabel: 'Yesterday · Aug 30, 2026 vs comparable Saturday',
    primaryKpiId: 'net-revenue',
    headline: 'Revenue appears down 5.1%, but the evidence does not agree',
    subheadline: 'POS units are down while marketing attribution reports more completed orders. Reconcile before acting.',
    observed: 1288000,
    baseline: 1357000,
    delta: -69000,
    changePercent: -5.1,
    zScore: -1.7,
    historyDays: 182,
    comparableDays: 26,
    baselineType: 'same-day seasonal baseline',
    materiality: { absoluteImpact: '₹69k', threshold: '₹75k', relative: '-5.1%', thresholdRelative: '±5%', passed: 'borderline' },
    confidence: { score: 0.27, label: 'Low', status: 'abstain', reason: 'The POS feed and attribution feed disagree on order direction; marketing data is 26 hours stale.' },
    sparseHistory: false,
    contradictions: [
      { id: 'contradiction-orders', label: 'Order direction conflict', details: 'ERP completed orders −6.5%; marketing attributed orders +8.4%.', severity: 'high' },
      { id: 'contradiction-freshness', label: 'Freshness conflict', details: 'Marketing platform missed two hourly loads and is 26 hours behind its SLA.', severity: 'high' },
      { id: 'contradiction-scope', label: 'Scope mismatch', details: 'Campaign attribution includes a pilot audience excluded from the regional POS cohort.', severity: 'medium' },
    ],
    kpis: contradictionKpis,
    drivers: [
      { id: 'volume', label: 'Units / volume', category: 'Demand', contributionPercent: 48, contributionValue: -33100, signal: 'POS says units are down 6.5%, but the comparable attributed-order series is up 8.4%.', method: 'Conflicting-source comparison', controllability: 'unknown', evidenceIds: ['ev-conflict-pos', 'ev-conflict-ads'], confidence: 0.22, hypothesis: true },
      { id: 'paid-demand', label: 'Paid demand', category: 'Marketing', contributionPercent: 31, contributionValue: -21400, signal: 'Campaign spend rose 12%, but two hourly loads are missing and the pilot audience changes the denominator.', method: 'Freshness check + denominator audit', controllability: 'unknown', evidenceIds: ['ev-conflict-ads', 'ev-conflict-scope'], confidence: 0.19, hypothesis: true },
      { id: 'price', label: 'Price / discount', category: 'Commercial', contributionPercent: 21, contributionValue: -14500, signal: 'A discount is visible in the sales ledger, but its campaign mapping is incomplete.', method: 'Rule check with incomplete mapping', controllability: 'unknown', evidenceIds: ['ev-conflict-pos'], confidence: 0.35, hypothesis: true },
    ],
    evidence: [
      { id: 'ev-conflict-pos', sourceId: 'sales-ledger', title: 'POS cohort says demand softened', finding: 'Completed orders −6.5% and units −6.5% in the regional ERP cohort.', status: 'conflict', coverage: '100% of closed POS stores', method: 'Deterministic SQL-shaped aggregation', lineage: 'erp.order_lines → semantic.daily_sales → conflict_check' },
      { id: 'ev-conflict-ads', sourceId: 'marketing-platform', title: 'Attribution feed says demand grew', finding: 'Attributed orders +8.4%; two hourly loads missing; last successful refresh was 26 hours ago.', status: 'conflict', coverage: '82% campaign rows · stale', method: 'Freshness + source agreement rule', lineage: 'ads.hourly_campaign_stats → semantic.paid_demand → conflict_check' },
      { id: 'ev-conflict-scope', sourceId: 'marketing-platform', title: 'Cohorts are not comparable', finding: 'Pilot audience is included in attribution but excluded from the regional POS comparison.', status: 'conflict', coverage: 'Pilot audience metadata', method: 'Entitlement and cohort rule', lineage: 'ads.audience_membership → cohort_contract → conflict_check' },
    ],
    actions: [
      { id: 'reconcile-attribution', driverId: 'volume', lever: 'Data quality', action: 'Reconcile click IDs and pilot-audience membership with the marketing data owner before changing spend.', expectedImpact: 'Restore a comparable denominator; no revenue impact claimed until validated.', owner: 'Marketing analytics + data engineering', confidence: 'High', monitor: 'Source freshness, duplicate rate, and order-direction agreement.', rights: ['executive', 'marketing-analyst'] },
      { id: 'do-not-pause', driverId: 'paid-demand', lever: 'Risk guardrail', action: 'Keep current efficient campaigns at their existing cap; do not pause or scale on this signal alone.', expectedImpact: 'Avoid an irreversible budget move while evidence is contradictory.', owner: 'Growth lead', confidence: 'High', monitor: 'Hourly feed recovery and reconciled ROAS.', rights: ['executive', 'marketing-analyst'] },
    ],
  },
  'new-market': {
    id: 'new-market',
    label: 'New market launch',
    description: 'Positive movement with sparse history and no stable baseline.',
    periodLabel: 'Pilot days 1–11 · Aug 20–30, 2026',
    primaryKpiId: 'net-revenue',
    headline: 'New-market revenue is up 18.4% against a very small baseline',
    subheadline: 'The launch signal is encouraging, but 11 comparable days are not enough to call a trend or scale spend.',
    observed: 142000,
    baseline: 119900,
    delta: 22100,
    changePercent: 18.4,
    zScore: null,
    historyDays: 11,
    comparableDays: 11,
    baselineType: 'pilot launch-day average',
    materiality: { absoluteImpact: '₹22.1k', threshold: '₹75k', relative: '+18.4%', thresholdRelative: '±5%', passed: 'not enough history' },
    confidence: { score: 0.41, label: 'Guarded', status: 'clarify', reason: 'Only 11 comparable days exist; the seasonal baseline and pilot-store inclusion rule are not established.' },
    sparseHistory: true,
    contradictions: [],
    clarification: 'Confirm the launch baseline date and whether pilot stores should remain in the comparison cohort. Keep the test unchanged for seven more days.',
    kpis: newMarketKpis,
    drivers: [
      { id: 'traffic', label: 'Launch traffic', category: 'Demand', contributionPercent: 42, contributionValue: 9300, signal: 'Paid sessions rose 16%, but the sample is only 11 days and channel mix is still changing.', method: 'Small-sample comparison', controllability: 'medium', evidenceIds: ['ev-new-market-ads'], confidence: 0.46, hypothesis: true },
      { id: 'availability', label: 'Launch availability', category: 'Supply', contributionPercent: 34, contributionValue: 7500, signal: 'In-stock is healthy at 96.1%, but only 4 of the 11 days contain a full assortment.', method: 'Coverage-adjusted contribution', controllability: 'medium', evidenceIds: ['ev-new-market-inventory'], confidence: 0.43, hypothesis: true },
      { id: 'mix', label: 'Early adopter mix', category: 'Merchandising', contributionPercent: 24, contributionValue: 5300, signal: 'AOV is flat; early orders are concentrated in two launch bundles with unknown repeat behavior.', method: 'Sparse mix scan', controllability: 'low', evidenceIds: ['ev-new-market-sales'], confidence: 0.38, hypothesis: true },
    ],
    evidence: [
      { id: 'ev-new-market-sales', sourceId: 'sales-ledger', title: 'Launch cohort is only 11 days old', finding: '₹1.42L revenue across 1,880 units; no year-over-year or seasonal comparator exists.', status: 'limited', coverage: '11 days · 3 pilot stores', method: 'Sparse-history rule', lineage: 'erp.order_lines → semantic.pilot_sales → launch_signal' },
      { id: 'ev-new-market-ads', sourceId: 'marketing-platform', title: 'Traffic is moving, but the mix is unstable', finding: 'Paid sessions +16%; channel mix changed on four of 11 days.', status: 'limited', coverage: '11 days · hourly campaign grain', method: 'Small-sample comparison', lineage: 'ads.hourly_campaign_stats → semantic.pilot_demand → launch_signal' },
      { id: 'ev-new-market-inventory', sourceId: 'inventory-wms', title: 'Availability is not the current constraint', finding: 'In-stock 96.1%; full assortment was present on only four days.', status: 'limited', coverage: '4 full-assortment days', method: 'Coverage check', lineage: 'wms.inventory_snapshots → semantic.pilot_availability → launch_signal' },
    ],
    actions: [
      { id: 'hold-pilot', driverId: 'traffic', lever: 'Experiment guardrail', action: 'Keep the current pilot budget and assortment unchanged for seven more days while the baseline accrues.', expectedImpact: 'Improve confidence; no incremental revenue claim until the cohort reaches 18 comparable days.', owner: 'Launch owner', confidence: 'Medium', monitor: 'Repeat rate, channel mix, in-stock coverage, and daily cohort size.', rights: ['executive', 'marketing-analyst'] },
      { id: 'capture-feedback', driverId: 'mix', lever: 'Learning loop', action: 'Ask Store 042 staff to tag customer objections and bundle requests during the pilot.', expectedImpact: 'Add qualitative evidence before changing assortment or pricing.', owner: 'Store 042 manager', confidence: 'Medium', monitor: 'Tagged objections and bundle conversion.', rights: ['store-manager'] },
    ],
  },
};

export const DEFAULT_FEEDBACK = [
  { id: 'seed-1', scenarioId: 'revenue-drop', personaId: 'executive', label: 'confirmed-driver', driverId: 'stockouts', createdAt: '2026-08-29T16:20:00+05:30' },
  { id: 'seed-2', scenarioId: 'revenue-drop', personaId: 'store-manager', label: 'useful', driverId: 'stockouts', createdAt: '2026-08-29T17:05:00+05:30' },
  { id: 'seed-3', scenarioId: 'contradictory-evidence', personaId: 'marketing-analyst', label: 'needs-review', driverId: 'volume', createdAt: '2026-08-30T09:15:00+05:30' },
];
